steps:
  - name: 'gcr.io/cloud-builders/go:1.18'
    id: 'go-build'
    args:
      - '-c'
      - |
        cd /workspace
        go env
        GOOS=linux GOARCH=amd64 make build
        cp /workspace/vault/plugins/vault-plugin-aead /workspace/docker/
    entrypoint: /bin/sh
  - name: gcr.io/cloud-builders/docker
    id: 'container-build'
    waitFor: ['go-build']
    args:
      - build
      - '-t'
      - '${_TARGET}:${SHORT_SHA}'
      - .
    dir: docker
timeout: 1200s
images:
  - '${_TARGET}:${SHORT_SHA}'
logsBucket: 'gs://vf-grp-clouddmz-lab-logging'
options:
  workerPool: projects/vf-grp-clouddmz-lab/locations/europe-west1/workerPools/worker-pool2
  env:
    - 'GOPRIVATE=github.com/pierrec,google.golang.org'
    - GOOS=linux
    - GOARCH=amd64
