steps:
  - name: 'golang:1.17'
    id: 'go-test'
    args:
      - '-c'
      - |
        go get -u github.com/Vodafone/vault-plugin-aead
        export GOPRIVATE=github.com/pierrec,google.golang.org
        go test -v -race
    entrypoint: /bin/bash
  - name: 'golang:1.17'
    id: 'go-build'
    waitFor: ['go-test']
    args:
      - '-c'
      - |
        go get -u github.com/Vodafone/vault-plugin-aead
        export GOPRIVATE=github.com/pierrec,google.golang.org
        go env
        make build
        cp vault/plugins/vault-plugin-aead docker/vault-plugin-aead
        echo `cat version/version.go | grep const | awk -F'"' '{print $2}'` > /workspace/version.txt
        cat /workspace/version.txt
    entrypoint: /bin/bash
  - name: gcr.io/cloud-builders/docker
    id: 'container-builder'
    waitFor: ['go-build']
    args:
      - build
      - '-t'
      - '${_TARGET}:${SHORT_SHA}$(cat /workspace/version.txt)'
      - .
    dir: docker
# images:
#   - '${_TARGET}:${SHORT_SHA}'
logsBucket: 'gs://vf-grp-clouddmz-lab-logging'
options:
  workerPool: projects/vf-grp-clouddmz-lab/locations/europe-west1/workerPools/worker-pool2