steps:
  - name: 'gcr.io/cloud-builders/go'
    id: 'go-build'
    args:
      - '-c'
      - |
        go get -u github.com/Vodafone/vault-plugin-aead
        go env
        cd /workspace
        make build
        cp /workspace/vault/plugins/vault-plugin-aead /workspace/docker/vault-plugin-aead
    entrypoint: /bin/sh
  - name: gcr.io/cloud-builders/docker
    id: 'container-build'
    waitFor: ['go-build']
    args:
      - build
      - '-t'
      - '${_TARGET}:${SHORT_SHA}'
      - .
    dir: docker
timeout: 1200s
images:
  - '${_TARGET}:${SHORT_SHA}'
logsBucket: 'gs://vf-grp-clouddmz-lab-logging'
options:
  workerPool: projects/vf-grp-clouddmz-lab/locations/europe-west1/workerPools/worker-pool2
  env:
    - 'GOPROXY=direct'
    - 'GOPRIVATE=github.com/pierrec,google.golang.org'
    - 'GOOS=linux'
    - 'GOARCH=amd64'
